t = linspace(1,99,1000);

data.PTx = 10;
data.f =  4562;
data.q = 50;
data.wa = 500;
data.heff = 186.4617;
data.area = 'Suburban';
data.d_v = 500;
data.path_c = {'Land'};
data.pathinfo = 1;
data.h2 = 3.34;
data.ha = 95.5;
data.htter = 543.7;
data.hrter = 428.1;
data.hb = [];

data.R1 = 0;
data.R2 = 0;
data.eff1 = 0;
data.eff2 = 0;
data.tca = 0;
data.debug = 0;
data.fid_log = -1;

% following P.1546-7
data.tcorr = 0;

for ii = 1:length(t)

    data.t = t(ii);


 [Es, L]  =  P1546FieldStrMixed(...
             data.f, ...
             data.t,...
             data.heff,...
             data.h2,...
             data.R2,...
             data.area,...
             data.d_v,...
             data.path_c,...
             data.pathinfo,...
             'q', data.q,...
             'wa', data.wa,...
             'PTx', data.PTx,...
             'ha', data.ha,...
             'hb', data.hb,...
             'R1', data.R1,...
             'tca', data.tca,...
             'htter', data.htter,...
             'hrter', data.hrter,...
             'eff1', data.eff1,...
             'eff2', data.eff2,...
             'debug', data.debug, ...
             'fid_log', data.fid_log, ...
             'tcorr', data.tcorr ...
            );


    Lb(ii) = L;
end

plot(t, Lb, 'LineWidth', 1, 'Color', 'b')

% following P.1546-7 with additional approximation for t>50 in troposcatter
data.tcorr = 1;

for ii = 1:length(t)

    data.t = t(ii);


 [Es, L]  =  P1546FieldStrMixed(...
             data.f, ...
             data.t,...
             data.heff,...
             data.h2,...
             data.R2,...
             data.area,...
             data.d_v,...
             data.path_c,...
             data.pathinfo,...
             'q', data.q,...
             'wa', data.wa,...
             'PTx', data.PTx,...
             'ha', data.ha,...
             'hb', data.hb,...
             'R1', data.R1,...
             'tca', data.tca,...
             'htter', data.htter,...
             'hrter', data.hrter,...
             'eff1', data.eff1,...
             'eff2', data.eff2,...
             'debug', data.debug, ...
             'fid_log', data.fid_log, ...
             'tcorr', data.tcorr ...
            );


    Lb_ts(ii) = L;
end

hold on
plot(t, Lb_ts, 'LineWidth', 1, 'Color', 'r', 'LineStyle', '--');

xlabel('Time Percentage (%)')
ylabel('Transmission Loss (dB)')
legend('ITU-R P.1546-7', 'ITU-R P.1546-7 w tropo correction')

set(gca,'FontSize', 14)
grid on